Algoritmo "ATIVIDADE 18"
//18. FUA para calcular a média de quatro números inteiros e
//exibir o resultado final.
Var
a, b, c, d, media: real


Inicio
escreva("Digite um número: ")
leia(a)
escreva("Digite outro número: ")
leia(b)
escreva("Digite mais um número: ")
leia(c)
escreva("Digite um último número: ")
leia(d)
media<- (a+b+c+d)/4

escreva("A média entre os 4 números é: ", media)

Fimalgoritmo