Algoritmo "Exercicio 11"
// Exercício 11! Para ler três números quaisquer e calcular a media aritmética entre eles.
//Escrever os números lidos e a media calculada.
Var
a, b, c, media: real


Inicio
escreva("digite o primeiro número: ")
leia(a)
escreva("Digite o segundo número: ")
leia(b)
escreva("Digite o terceiro número: ")
leia(c)
media<- (a+b+c)/3
escreva("A média de ", a, " e", b, " e", c, " é: ", media)

Fimalgoritmo