Algoritmo "ATIVIDADE 14"
//14. FUA para ler os seguintes números: A, B e C. Após, calcular o valor de D
//segundo a expressão: D = B2 - 4AC e mostrar os valores lidos e o resultado.
Var
a, b, c, d: inteiro
resultado: real


Inicio
escreva("Digite um número:")
leia(a)
escreva("Digite outro número:")
leia(b)
escreva("Digite mais um número:")
leia(c)

resultado<- b*2 - 4*a*c

escreval(b, " x 2 - 4 x", a, " x", c)
escreval("O resultado do calcúlo é: ", resultado)

Fimalgoritmo