Algoritmo "Exercicio 3"
//3. Poema
//Faça um programa que, usando um único comando WriteLine, escreva na tela o seguinte texto:
//Batatinha quando nasce
//se esparrama pelo chão.
//Menininha quando dorme
//põe a mão no coração.

Var
dig:caracter


Inicio
escreva("Escreva qualquer coisa e ganhe um poema: ")
leia(dig)
escreval("")
escreval("Batatinha quando nasce")
escreval("Se esparrama pelo chão")
escreval("Menininha quando dorme")
escreval("Põe a mão no coração")

Fimalgoritmo