Algoritmo "Exercicio 1"
//1. Faça um programa que leia as seguintes informações:
//Nome de um aluno
//Endereço
//Telefone.
//Depois de ler essas informações, exiba todas novamente em vídeo.
Var
nome, end:caracter
fone:caracter

Inicio
escreva("Informe seu nome:")
leia(nome)
escreva("Informe seu endereço:")
leia(end)
escreva("Informe seu telefone:")
leia(fone)
escreval("Seu nome é:",nome)
escreval("Reside no endereço:",end)
escreval("Número do telefone:",fone)

Fimalgoritmo