Algoritmo "Exercicio 3"
//3. Poema
//Faça um programa que, usando um único comando WriteLine, escreva na tela o seguinte texto:
//Batatinha quando nasce
//se esparrama pelo chão.
//Menininha quando dorme
//põe a mão no coração.
Var
poema:caracter

Inicio
escreva("Digite qualquer coisa e ganhe um poema:")
leia(poema)
escreval("")
escreval("Batatinha quando nasce")
escreval("Se esparra pelo chão")
escreval("Menininha quando nasce")
escreval("Põe a mão no coração")

Fimalgoritmo