Algoritmo "Exercicio 1"
//1. Faça um programa que leia as seguintes informações:
//Nome de um aluno
//Endereço
//Telefone.
//Depois de ler essas informações, exiba todas novamente em vídeo.
Var
nome, end:caracter
tel:inteiro


Inicio

escreva("Informe seu nome: ")
leia(nome)
escreva("Informe seu endereço: ")
leia(end)
escreva("Informe seu telefone:" )
leia(tel)
escreval(nome, ",", end, " ,", tel, ".")

Fimalgoritmo