Algoritmo "Exercicio 9"
//9. Dia da Semana
//Solicite um dia da semana (número inteiro) e seu programa deverá informar por extenso qual é o dia. EX: 1 =
//domingo.

var
dia:inteiro

Inicio
escreva("Informe de 1 a 7 para o dia da semana: ")
leia(dia)
escolha (dia)
caso 1
escreva("Domingo!")
caso 2
escreva("Segunda!")
caso 3
escreva("Terça!")
caso 4
escreva("Quarta!")
caso 5
escreva("Quinta!")
caso 6
escreva("Sexta!")
caso 7
escreva("Sábado!")
fimescolha

Fimalgoritmo